// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yielxhxelfpapciwxsrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpZWx4aHhlbGZwYXBjaXd4c3JjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5OTA3NTEsImV4cCI6MjA2NDU2Njc1MX0.B4eAoz6X9sr6qA9HPd_ZEzx8gccpAdNlHlJ42EaV-lU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);